### PR TITLE
Upgrade golang and codegen

### PR DESCRIPTION
**Pull request by 314159**
Hi,

Thank you for making this Docker file -- it's just what I needed, with a couple of minor changes:
1. I've gone with go lang 1.20
2. I've let docker pick the latest patch release of `oapi-codegen` 1.12 (today it is 1.12.4)

### CODE REVIEW

**Comment by ppaulweber** [comment]
@314159 the idea is to use this repository to deploy at `ghcr.io` always a specific version through the `Dockerfile` configuration, so if you wanna merge this PR can you change than this to the explicit version of `1.12.4`? thx

If you are ready, please assign me as reviewer and I'll merge the PR and then tag the repository with that version in order to trigger a `ghcr.io` deployment of the `docker` image.

**Review by ppaulweber — CHANGES_REQUESTED** [review]
@314159 the idea is to use this repository to deploy at `ghcr.io` always a specific version through the `Dockerfile` configuration, so if you wanna merge this PR can you change than this to the explicit version of `1.12.4`? thx

If you are ready, please assign me as reviewer and I'll merge the PR and then tag the repository with that version in order to trigger a `ghcr.io` deployment of the `docker` image.

**Comment by 314159** [comment]
@ppaulweber Ok, that's fine. I'll make the change tomorrow when I get to my office.

**Comment by 314159** [comment]
@ppaulweber What about the version of Go? Right now it also will use the latest patch level, but that also can be nailed down if you wish.

**Comment by ppaulweber** [comment]
> What about the version of Go? Right now it also will use the latest patch level, but that also can be nailed down if you wish.

@314159 I would go not higher than `1.19`, because `1.20` includes still a lot of experimental stuff, which is for sure not needed in this case.

**Comment by 314159** [comment]
Ok, which 1.19.x? 1.19.6 or the _latest_ 1.19?

**Comment by 314159** [comment]
@ppaulweber I've decided to only change the version of oapi-codegen for now.  I'll make a separate PR for the golang version later.

**Review by ppaulweber — APPROVED** [review]
LGTM :+1:

**Comment by ppaulweber** [comment]
FYI @314159: the latest image is already released, see: https://github.com/fiskaly/docker.oapi-codegen/pkgs/container/docker.oapi-codegen

**Pull request merged**
